<script>
import throttle from 'lodash/throttle';
import emptySvg from '@gitlab/svgs/dist/illustrations/empty-state/empty-activity-md.svg';
import GlDropdownItem from '../../../base/dropdown/dropdown_item.vue';
import GlCard from '../../../base/card/card.vue';
import GlEmptyState from '../../../regions/empty_state/empty_state.vue';
import GlButton from '../../../base/button/button.vue';
import GlAlert from '../../../base/alert/alert.vue';
import GlFormInputGroup from '../../../base/form/form_input_group/form_input_group.vue';
import GlFormTextarea from '../../../base/form/form_textarea/form_textarea.vue';
import GlForm from '../../../base/form/form.vue';
import GlFormText from '../../../base/form/form_text/form_text.vue';
import GlExperimentBadge from '../../experiment_badge/experiment_badge.vue';
import { badgeTypes, badgeTypeValidator } from '../../experiment_badge/constants';
import { SafeHtmlDirective as SafeHtml } from '../../../../directives/safe_html/safe_html';
import GlDuoChatLoader from './components/duo_chat_loader/duo_chat_loader.vue';
import GlDuoChatPredefinedPrompts from './components/duo_chat_predefined_prompts/duo_chat_predefined_prompts.vue';
import GlDuoChatConversation from './components/duo_chat_conversation/duo_chat_conversation.vue';
import { CHAT_RESET_MESSAGE } from './constants';

export const i18n = {
  CHAT_DEFAULT_TITLE: 'GitLab Duo Chat',
  CHAT_CLOSE_LABEL: 'Close the Code Explanation',
  CHAT_LEGAL_GENERATED_BY_AI: 'Responses generated by AI',
  CHAT_EMPTY_STATE_TITLE: 'Ask a question',
  CHAT_EMPTY_STATE_DESC: 'AI generated explanations will appear here.',
  CHAT_PROMPT_PLACEHOLDER_DEFAULT: 'GitLab Duo Chat',
  CHAT_PROMPT_PLACEHOLDER_WITH_COMMANDS: 'Type "/" for slash commands',
  CHAT_SUBMIT_LABEL: 'Send chat message.',
  CHAT_LEGAL_DISCLAIMER:
    "May provide inappropriate responses not representative of GitLab's views. Do not input personal data.",
  CHAT_DEFAULT_PREDEFINED_PROMPTS: [
    'How do I change my password in GitLab?',
    'How do I fork a project?',
    'How do I clone a repository?',
    'How do I create a template?',
  ],
};

const isMessage = (item) => Boolean(item) && item?.role;
const isSlashCommand = (command) => Boolean(command) && command?.name && command.description;

// eslint-disable-next-line unicorn/no-array-callback-reference
const itemsValidator = (items) => items.every(isMessage);
// eslint-disable-next-line unicorn/no-array-callback-reference
const slashCommandsValidator = (commands) => commands.every(isSlashCommand);

export default {
  name: 'GlDuoChat',
  components: {
    GlEmptyState,
    GlButton,
    GlAlert,
    GlFormInputGroup,
    GlFormTextarea,
    GlForm,
    GlFormText,
    GlExperimentBadge,
    GlDuoChatLoader,
    GlDuoChatPredefinedPrompts,
    GlDuoChatConversation,
    GlCard,
    GlDropdownItem,
  },
  directives: {
    SafeHtml,
  },
  props: {
    /**
     * The title of the chat/feature.
     */
    title: {
      type: String,
      required: false,
      default: i18n.CHAT_DEFAULT_TITLE,
    },
    /**
     * Array of messages to display in the chat.
     */
    messages: {
      type: Array,
      required: false,
      default: () => [],
      validator: itemsValidator,
    },
    /**
     * A non-recoverable error message to display in the chat.
     */
    error: {
      type: String,
      required: false,
      default: '',
    },
    /**
     * Whether the chat is currently fetching a response from AI.
     */
    isLoading: {
      type: Boolean,
      required: false,
      default: false,
    },
    /**
     * Whether the conversational interfaces should be enabled.
     */
    isChatAvailable: {
      type: Boolean,
      required: false,
      default: true,
    },
    /**
     * Array of predefined prompts to display in the chat to start a conversation.
     */
    predefinedPrompts: {
      type: Array,
      required: false,
      default: () => i18n.CHAT_DEFAULT_PREDEFINED_PROMPTS,
    },
    /**
     * URL to the help page. This is passed down to the `GlExperimentBadge` component.
     */
    badgeHelpPageUrl: {
      type: String,
      required: false,
      default: '',
    },
    /**
     * The type of the badge. This is passed down to the `GlExperimentBadge` component. Refer that component for more information.
     */
    badgeType: {
      type: String || null,
      required: false,
      default: badgeTypes[0],
      validator: badgeTypeValidator,
    },
    /**
     * The current tool's name to display in the loading message while waiting for a response from AI. Refer the `GlDuoChatLoader` component for more information.
     */
    toolName: {
      type: String,
      required: false,
      default: i18n.CHAT_DEFAULT_TITLE,
    },
    /**
     * Array of slash commands to display in the chat.
     */
    slashCommands: {
      type: Array,
      required: false,
      default: () => [],
      validator: slashCommandsValidator,
    },
    /**
     * Whether the header should be displayed.
     */
    showHeader: {
      type: Boolean,
      required: false,
      default: true,
    },
    /**
     * Override the default empty state title text.
     */
    emptyStateTitle: {
      type: String,
      required: false,
      default: i18n.CHAT_EMPTY_STATE_TITLE,
    },
    /**
     * Override the default empty state description text.
     */
    emptyStateDescription: {
      type: String,
      required: false,
      default: i18n.CHAT_EMPTY_STATE_DESC,
    },
    /**
     * Override the default chat prompt placeholder text.
     */
    chatPromptPlaceholder: {
      type: String,
      required: false,
      default: '',
    },
  },
  data() {
    return {
      isHidden: false,
      prompt: '',
      scrolledToBottom: true,
      activeCommandIndex: 0,
    };
  },
  computed: {
    withSlashCommands() {
      return this.slashCommands.length > 0;
    },
    hasMessages() {
      return this.messages?.length > 0;
    },
    conversations() {
      if (!this.hasMessages) return [];

      return this.messages.reduce(
        (acc, message) => {
          if (message.content === CHAT_RESET_MESSAGE) {
            acc.push([]);
          } else {
            acc[acc.length - 1].push(message);
          }
          return acc;
        },
        [[]]
      );
    },
    lastMessage() {
      return this.messages[this.messages.length - 1];
    },
    resetDisabled() {
      if (this.isLoading || !this.hasMessages) {
        return true;
      }
      return this.lastMessage?.content === CHAT_RESET_MESSAGE;
    },
    submitDisabled() {
      return this.isLoading || this.isStreaming;
    },
    isStreaming() {
      return Boolean(
        (this.lastMessage?.chunks?.length > 0 && !this.lastMessage?.content) ||
          typeof this.lastMessage?.chunkId === 'number'
      );
    },
    filteredSlashCommands() {
      const caseInsensitivePrompt = this.prompt.toLowerCase();
      return this.slashCommands.filter((c) =>
        c.name.toLowerCase().startsWith(caseInsensitivePrompt)
      );
    },
    shouldShowSlashCommands() {
      if (!this.withSlashCommands) return false;
      const caseInsensitivePrompt = this.prompt.toLowerCase();
      const startsWithSlash = caseInsensitivePrompt.startsWith('/');
      const startsWithSlashCommand = this.slashCommands.some((c) =>
        caseInsensitivePrompt.startsWith(c.name)
      );
      return startsWithSlash && this.filteredSlashCommands.length && !startsWithSlashCommand;
    },
    inputPlaceholder() {
      if (this.chatPromptPlaceholder) {
        return this.chatPromptPlaceholder;
      }

      return this.withSlashCommands
        ? i18n.CHAT_PROMPT_PLACEHOLDER_WITH_COMMANDS
        : i18n.CHAT_PROMPT_PLACEHOLDER_DEFAULT;
    },
  },
  watch: {
    isLoading() {
      this.isHidden = false;
      this.scrollToBottom();
    },
  },
  created() {
    this.handleScrollingTrottled = throttle(this.handleScrolling, 200); // Assume a 200ms throttle for example
  },
  mounted() {
    this.scrollToBottom();
  },
  methods: {
    hideChat() {
      this.isHidden = true;
      /**
       * Emitted when clicking the cross in the title and the chat gets closed.
       */
      this.$emit('chat-hidden');
    },
    sendChatPrompt() {
      if (this.submitDisabled) {
        return;
      }
      if (this.prompt) {
        if (this.prompt === CHAT_RESET_MESSAGE && this.resetDisabled) {
          return;
        }
        /**
         * Emitted when a new user prompt should be sent out.
         *
         * @param {String} prompt The user prompt to send.
         */
        this.$emit('send-chat-prompt', this.prompt.trim());
        this.setPromptAndFocus();
      }
    },
    sendPredefinedPrompt(prompt) {
      this.prompt = prompt;
      this.sendChatPrompt();
    },
    handleScrolling(event) {
      const { scrollTop, offsetHeight, scrollHeight } = event.target;
      this.scrolledToBottom = scrollTop + offsetHeight >= scrollHeight;
    },
    async scrollToBottom() {
      await this.$nextTick();

      this.$refs.anchor?.scrollIntoView?.();
    },
    onTrackFeedback(event) {
      /**
       * Notify listeners about the feedback form submission on a response message.
       * @param {*} event An event, containing the feedback choices and the extended feedback text.
       */
      this.$emit('track-feedback', event);
    },
    onInputKeyup(e) {
      const { metaKey, ctrlKey, altKey, shiftKey } = e;

      if (this.shouldShowSlashCommands) {
        e.preventDefault();

        if (e.key === 'Enter') {
          this.selectSlashCommand(this.activeCommandIndex);
        } else if (e.key === 'ArrowUp') {
          this.prevCommand();
        } else if (e.key === 'ArrowDown') {
          this.nextCommand();
        } else {
          this.activeCommandIndex = 0;
        }
      } else if (e.key === 'Enter' && !(metaKey || ctrlKey || altKey || shiftKey)) {
        e.preventDefault();
        this.sendChatPrompt();
      }
    },
    prevCommand() {
      this.activeCommandIndex -= 1;
      this.wrapCommandIndex();
    },
    nextCommand() {
      this.activeCommandIndex += 1;
      this.wrapCommandIndex();
    },
    wrapCommandIndex() {
      if (this.activeCommandIndex < 0) {
        this.activeCommandIndex = this.filteredSlashCommands.length - 1;
      } else if (this.activeCommandIndex >= this.filteredSlashCommands.length) {
        this.activeCommandIndex = 0;
      }
    },
    async setPromptAndFocus(prompt = '') {
      this.prompt = prompt;
      await this.$nextTick();
      this.$refs.prompt.$el.focus();
    },
    selectSlashCommand(index) {
      const command = this.filteredSlashCommands[index];
      if (command.shouldSubmit) {
        this.prompt = command.name;
        this.sendChatPrompt();
      } else {
        this.setPromptAndFocus(`${command.name} `);
      }
    },
  },
  i18n,
  emptySvg,
};
</script>
<template>
  <aside
    v-if="!isHidden"
    id="chat-component"
    class="markdown-code-block duo-chat-drawer gl-max-h-full gl-bottom-0 gl-shadow-none gl-border-l gl-border-t duo-chat"
    role="complementary"
    data-testid="chat-component"
  >
    <header
      v-if="showHeader"
      data-testid="chat-header"
      class="duo-chat-drawer-header duo-chat-drawer-header-sticky gl-z-index-200 gl-p-0! gl-border-b-0"
    >
      <div
        class="drawer-title gl-display-flex gl-justify-content-start gl-align-items-center gl-p-5"
      >
        <h3 class="gl-my-0 gl-font-size-h2">{{ title }}</h3>
        <gl-experiment-badge
          v-if="badgeType"
          :help-page-url="badgeHelpPageUrl"
          :type="badgeType"
          container-id="chat-component"
        />
        <gl-button
          category="tertiary"
          variant="default"
          icon="close"
          size="small"
          class="gl-p-0! gl-ml-auto"
          data-testid="chat-close-button"
          :aria-label="$options.i18n.CHAT_CLOSE_LABEL"
          @click="hideChat"
        />
      </div>

      <gl-alert
        :dismissible="false"
        variant="tip"
        :show-icon="false"
        class="gl-text-center gl-border-t gl-p-4 gl-text-gray-700 gl-bg-gray-50 legal-warning gl-max-w-full"
        role="alert"
        data-testid="chat-legal-warning"
        >{{ $options.i18n.CHAT_LEGAL_GENERATED_BY_AI }}</gl-alert
      >

      <!--
        @slot Subheader to be rendered right after the title. It is sticky and stays on top of the chat no matter the number of messages.
      -->
      <slot name="subheader"></slot>

      <!-- Ensure that the global error is not scrolled away -->
      <gl-alert
        v-if="error"
        key="error"
        :dismissible="false"
        variant="danger"
        class="gl-pl-9!"
        role="alert"
        data-testid="chat-error"
      >
        <span v-safe-html="error"></span>
      </gl-alert>
    </header>

    <div class="duo-chat-drawer-body" data-testid="chat-history" @scroll="handleScrollingTrottled">
      <transition-group
        tag="section"
        name="message"
        class="duo-chat-history gl-display-flex gl-flex-direction-column gl-justify-content-end gl-bg-gray-10"
        :class="[
          {
            'gl-h-full': !hasMessages,
            'force-scroll-bar': hasMessages,
          },
        ]"
      >
        <gl-duo-chat-conversation
          v-for="(conversation, index) in conversations"
          :key="`conversation-${index}`"
          :messages="conversation"
          :show-delimiter="index > 0"
          @track-feedback="onTrackFeedback"
        />
        <template v-if="!hasMessages && !isLoading">
          <gl-empty-state
            key="empty-state"
            :svg-path="$options.emptySvg"
            :svg-height="145"
            :title="emptyStateTitle"
            :description="emptyStateDescription"
            class="gl-flex-grow gl-justify-content-center"
          />
          <gl-duo-chat-predefined-prompts
            key="predefined-prompts"
            :prompts="predefinedPrompts"
            @click="sendPredefinedPrompt"
          />
        </template>
        <gl-duo-chat-loader v-if="isLoading" key="loader" :tool-name="toolName" />
        <div key="anchor" ref="anchor" class="scroll-anchor"></div>
      </transition-group>
    </div>
    <footer
      v-if="isChatAvailable"
      data-testid="chat-footer"
      class="duo-chat-drawer-footer duo-chat-drawer-footer-sticky gl-p-5 gl-border-t gl-bg-gray-10"
      :class="{ 'duo-chat-drawer-body-scrim-on-footer': !scrolledToBottom }"
    >
      <gl-form data-testid="chat-prompt-form" @submit.stop.prevent="sendChatPrompt">
        <gl-form-input-group>
          <div
            class="duo-chat-input gl-flex-grow-1 gl-vertical-align-top gl-max-w-full gl-min-h-8 gl-inset-border-1-gray-400 gl-rounded-base gl-bg-white"
            :data-value="prompt"
          >
            <gl-card
              v-if="shouldShowSlashCommands"
              ref="commands"
              class="slash-commands !gl-absolute gl-translate-y-n100 gl-list-style-none gl-pl-0 gl-w-full gl-shadow-md"
              body-class="gl-p-2!"
            >
              <gl-dropdown-item
                v-for="(command, index) in filteredSlashCommands"
                :key="command.name"
                :class="{ 'active-command': index === activeCommandIndex }"
                @mouseenter.native="activeCommandIndex = index"
                @click="selectSlashCommand(index)"
              >
                <span class="gl-display-flex gl-justify-content-space-between">
                  <span class="gl-display-block">{{ command.name }}</span>
                  <small class="gl-text-gray-500 gl-font-style-italic gl-text-right gl-pl-3">{{
                    command.description
                  }}</small>
                </span>
              </gl-dropdown-item>
            </gl-card>

            <gl-form-textarea
              ref="prompt"
              v-model="prompt"
              data-testid="chat-prompt-input"
              class="gl-absolute gl-h-full! gl-py-4! gl-bg-transparent! gl-rounded-top-right-none gl-rounded-bottom-right-none gl-shadow-none!"
              :class="{ 'gl-text-truncate': !prompt }"
              :placeholder="inputPlaceholder"
              autofocus
              @keydown.enter.exact.native.prevent
              @keyup.native="onInputKeyup"
            />
          </div>
          <template #append>
            <gl-button
              icon="paper-airplane"
              category="primary"
              variant="confirm"
              class="!gl-absolute gl-bottom-2 gl-right-2 gl-rounded-base!"
              type="submit"
              data-testid="chat-prompt-submit-button"
              :aria-label="$options.i18n.CHAT_SUBMIT_LABEL"
              :disabled="submitDisabled"
            />
          </template>
        </gl-form-input-group>
        <gl-form-text
          class="gl-text-gray-400 gl-line-height-20 gl-mt-3"
          data-testid="chat-legal-disclaimer"
          >{{ $options.i18n.CHAT_LEGAL_DISCLAIMER }}</gl-form-text
        >
      </gl-form>
    </footer>
  </aside>
</template>
