<script>
import throttle from 'lodash/throttle';
import emptySvg from '@gitlab/svgs/dist/illustrations/empty-state/empty-activity-md.svg';
import GlDropdownItem from '../../../base/dropdown/dropdown_item.vue';
import GlCard from '../../../base/card/card.vue';
import GlEmptyState from '../../../regions/empty_state/empty_state.vue';
import GlButton from '../../../base/button/button.vue';
import GlAlert from '../../../base/alert/alert.vue';
import GlFormInputGroup from '../../../base/form/form_input_group/form_input_group.vue';
import GlFormTextarea from '../../../base/form/form_textarea/form_textarea.vue';
import GlForm from '../../../base/form/form.vue';
import GlFormText from '../../../base/form/form_text/form_text.vue';
import GlExperimentBadge from '../../experiment_badge/experiment_badge.vue';
import { badgeTypes, badgeTypeValidator } from '../../experiment_badge/constants';
import { SafeHtmlDirective as SafeHtml } from '../../../../directives/safe_html/safe_html';
import GlDuoChatLoader from './components/duo_chat_loader/duo_chat_loader.vue';
import GlDuoChatPredefinedPrompts from './components/duo_chat_predefined_prompts/duo_chat_predefined_prompts.vue';
import GlDuoChatConversation from './components/duo_chat_conversation/duo_chat_conversation.vue';
import { CHAT_RESET_MESSAGE } from './constants';

export const i18n = {
  CHAT_DEFAULT_TITLE: 'GitLab Duo Chat',
  CHAT_CLOSE_LABEL: 'Close the Code Explanation',
  CHAT_LEGAL_GENERATED_BY_AI: 'Responses generated by AI',
  CHAT_EMPTY_STATE_TITLE: 'Ask a question',
  CHAT_EMPTY_STATE_DESC: 'AI generated explanations will appear here.',
  CHAT_PROMPT_PLACEHOLDER: 'GitLab Duo Chat',
  CHAT_SUBMIT_LABEL: 'Send chat message.',
  CHAT_LEGAL_DISCLAIMER:
    "May provide inappropriate responses not representative of GitLab's views. Do not input personal data.",
  CHAT_DEFAULT_PREDEFINED_PROMPTS: [
    'How do I change my password in GitLab?',
    'How do I fork a project?',
    'How do I clone a repository?',
    'How do I create a template?',
  ],
};

export const slashCommands = [
  {
    name: '/reset',
    shouldSubmit: true,
    description: 'Reset conversation, ignore the previous messages.',
  },
  {
    name: '/test',
    shouldSubmit: false,
    description: 'Write tests for the code snippet.',
  },
  {
    name: '/refactor',
    shouldSubmit: false,
    description: 'Refactor the code snippet.',
  },
  {
    name: '/explain',
    shouldSubmit: false,
    description: 'Explain the code snippet.',
  },
];

const isMessage = (item) => Boolean(item) && item?.role;

const itemsValidator = (items) => items.every(isMessage);

export default {
  name: 'GlDuoChat',
  components: {
    GlEmptyState,
    GlButton,
    GlAlert,
    GlFormInputGroup,
    GlFormTextarea,
    GlForm,
    GlFormText,
    GlExperimentBadge,
    GlDuoChatLoader,
    GlDuoChatPredefinedPrompts,
    GlDuoChatConversation,
    GlCard,
    GlDropdownItem,
  },
  directives: {
    SafeHtml,
  },
  props: {
    /**
     * The title of the chat/feature.
     */
    title: {
      type: String,
      required: false,
      default: i18n.CHAT_DEFAULT_TITLE,
    },
    /**
     * Array of messages to display in the chat.
     */
    messages: {
      type: Array,
      required: false,
      default: () => [],
      validator: itemsValidator,
    },
    /**
     * A non-recoverable error message to display in the chat.
     */
    error: {
      type: String,
      required: false,
      default: '',
    },
    /**
     * Whether the chat is currently fetching a response from AI.
     */
    isLoading: {
      type: Boolean,
      required: false,
      default: false,
    },
    /**
     * Whether the conversational interfaces should be enabled.
     */
    isChatAvailable: {
      type: Boolean,
      required: false,
      default: true,
    },
    /**
     * Array of predefined prompts to display in the chat to start a conversation.
     */
    predefinedPrompts: {
      type: Array,
      required: false,
      default: () => i18n.CHAT_DEFAULT_PREDEFINED_PROMPTS,
    },
    /**
     * URL to the help page. This is passed down to the `GlExperimentBadge` component.
     */
    badgeHelpPageUrl: {
      type: String,
      required: false,
      default: '',
    },
    /**
     * The type of the badge. This is passed down to the `GlExperimentBadge` component. Refer that component for more information.
     */
    badgeType: {
      type: String,
      required: false,
      default: badgeTypes[0],
      validator: badgeTypeValidator,
    },
    /**
     * The current tool's name to display in the loading message while waiting for a response from AI. Refer the `GlDuoChatLoader` component for more information.
     */
    toolName: {
      type: String,
      required: false,
      default: i18n.CHAT_DEFAULT_TITLE,
    },
    /**
     * Whether the slash commands should be available to user when typing the prompt.
     */
    withSlashCommands: {
      type: Boolean,
      required: false,
      default: false,
    },
  },
  data() {
    return {
      isHidden: false,
      prompt: '',
      scrolledToBottom: true,
      activeCommandIndex: 0,
    };
  },
  computed: {
    hasMessages() {
      return this.messages?.length > 0;
    },
    conversations() {
      if (!this.hasMessages) return [];

      return this.messages.reduce(
        (acc, message) => {
          if (message.content === CHAT_RESET_MESSAGE) {
            acc.push([]);
          } else {
            acc[acc.length - 1].push(message);
          }
          return acc;
        },
        [[]]
      );
    },
    resetDisabled() {
      if (this.isLoading || !this.hasMessages) {
        return true;
      }

      const lastMessage = this.messages[this.messages.length - 1];
      return lastMessage.content === CHAT_RESET_MESSAGE;
    },
    filteredSlashCommands() {
      const caseInsensitivePrompt = this.prompt.toLowerCase();
      return slashCommands.filter((c) => c.name.toLowerCase().startsWith(caseInsensitivePrompt));
    },
    shouldShowSlashCommands() {
      if (!this.withSlashCommands) return false;
      const caseInsensitivePrompt = this.prompt.toLowerCase();
      const startsWithSlash = caseInsensitivePrompt.startsWith('/');
      const startsWithSlashCommand = slashCommands.some((c) =>
        caseInsensitivePrompt.startsWith(c.name)
      );
      return startsWithSlash && this.filteredSlashCommands.length && !startsWithSlashCommand;
    },
  },
  watch: {
    isLoading() {
      this.isHidden = false;
      this.scrollToBottom();
    },
    messages() {
      this.prompt = '';
    },
  },
  created() {
    this.handleScrollingTrottled = throttle(this.handleScrolling, 200); // Assume a 200ms throttle for example
  },
  mounted() {
    this.scrollToBottom();
  },
  methods: {
    hideChat() {
      this.isHidden = true;
      /**
       * Emitted when clicking the cross in the title and the chat gets closed.
       */
      this.$emit('chat-hidden');
    },
    sendChatPrompt() {
      if (this.prompt) {
        if (this.prompt === CHAT_RESET_MESSAGE && this.resetDisabled) {
          return;
        }
        /**
         * Emitted when a new user prompt should be sent out.
         *
         * @param {String} prompt The user prompt to send.
         */
        this.$emit('send-chat-prompt', this.prompt);
      }
    },
    sendPredefinedPrompt(prompt) {
      this.prompt = prompt;
      this.sendChatPrompt();
    },
    handleScrolling() {
      const { scrollTop, offsetHeight, scrollHeight } = this.$refs.drawer;
      this.scrolledToBottom = scrollTop + offsetHeight >= scrollHeight;
    },
    async scrollToBottom() {
      await this.$nextTick();

      if (this.$refs.drawer) {
        this.$refs.drawer.scrollTop = this.$refs.drawer.scrollHeight;
      }
    },
    onTrackFeedback(event) {
      /**
       * Notify listeners about the feedback form submission on a response message.
       * @param {*} event An event, containing the feedback choices and the extended feedback text.
       */
      this.$emit('track-feedback', event);
    },
    onInputKeyup(e) {
      const { metaKey, ctrlKey, altKey, shiftKey } = e;

      if (this.shouldShowSlashCommands) {
        e.preventDefault();

        if (e.key === 'Enter') {
          this.selectSlashCommand(this.activeCommandIndex);
        } else if (e.key === 'ArrowUp') {
          this.prevCommand();
        } else if (e.key === 'ArrowDown') {
          this.nextCommand();
        } else {
          this.activeCommandIndex = 0;
        }
      } else if (e.key === 'Enter' && !(metaKey || ctrlKey || altKey || shiftKey)) {
        e.preventDefault();
        this.sendChatPrompt();
      }
    },
    prevCommand() {
      this.activeCommandIndex -= 1;
      this.wrapCommandIndex();
    },
    nextCommand() {
      this.activeCommandIndex += 1;
      this.wrapCommandIndex();
    },
    wrapCommandIndex() {
      if (this.activeCommandIndex < 0) {
        this.activeCommandIndex = this.filteredSlashCommands.length - 1;
      } else if (this.activeCommandIndex >= this.filteredSlashCommands.length) {
        this.activeCommandIndex = 0;
      }
    },
    selectSlashCommand(index) {
      const command = this.filteredSlashCommands[index];
      if (command.shouldSubmit) {
        this.prompt = command.name;
        this.sendChatPrompt();
      } else {
        this.prompt = `${command.name} `;
        this.$refs.prompt.$el.focus();
      }
    },
  },
  i18n,
  emptySvg,
};
</script>
<template>
  <aside
    v-if="!isHidden"
    id="chat-component"
    ref="drawer"
    class="markdown-code-block gl-drawer gl-drawer-default gl-max-h-full gl-bottom-0 gl-shadow-none gl-border-l gl-border-t duo-chat"
    role="complementary"
    data-testid="chat-component"
    @scroll="handleScrollingTrottled"
  >
    <header class="gl-drawer-header gl-drawer-header-sticky gl-z-index-200 gl-p-0! gl-border-b-0">
      <div
        class="drawer-title gl-display-flex gl-justify-content-start gl-align-items-center gl-p-5"
      >
        <h3 class="gl-my-0 gl-font-size-h2">{{ title }}</h3>
        <gl-experiment-badge
          :help-page-url="badgeHelpPageUrl"
          :type="badgeType"
          container-id="chat-component"
        />
        <gl-button
          category="tertiary"
          variant="default"
          icon="close"
          size="small"
          class="gl-p-0! gl-ml-auto"
          data-testid="chat-close-button"
          :aria-label="$options.i18n.CHAT_CLOSE_LABEL"
          @click="hideChat"
        />
      </div>

      <gl-alert
        :dismissible="false"
        variant="tip"
        :show-icon="false"
        class="gl-text-center gl-border-t gl-p-4 gl-text-gray-700 gl-bg-gray-50 legal-warning gl-max-w-full"
        role="alert"
        data-testid="chat-legal-warning"
        >{{ $options.i18n.CHAT_LEGAL_GENERATED_BY_AI }}</gl-alert
      >

      <!--
        @slot Subheader to be rendered right after the title. It is sticky and stays on top of the chat no matter the number of messages.
      -->
      <slot name="subheader"></slot>
    </header>

    <div class="gl-drawer-body gl-display-flex gl-flex-direction-column">
      <!-- @slot 'Hero' information to be rendered at the top of the chat before any message. It gets pushed away from the view by incomming messages
      -->
      <slot name="hero"></slot>

      <gl-alert
        v-if="error"
        key="error"
        :dismissible="false"
        variant="danger"
        class="gl-mb-0 gl-pl-9!"
        role="alert"
        data-testid="chat-error"
        ><span v-safe-html="error"></span
      ></gl-alert>

      <section
        class="gl-display-flex gl-flex-direction-column gl-justify-content-end gl-flex-grow-1 gl-border-b-0 gl-bg-gray-10"
      >
        <transition-group
          tag="div"
          name="message"
          class="gl-display-flex gl-flex-direction-column gl-justify-content-end"
          :class="[
            {
              'gl-h-full': !hasMessages,
              'gl-h-auto': hasMessages,
            },
          ]"
        >
          <gl-duo-chat-conversation
            v-for="(conversation, index) in conversations"
            :key="`conversation-${index}`"
            :messages="conversation"
            :show-delimiter="index > 0"
            @track-feedback="onTrackFeedback"
          />
          <template v-if="!hasMessages && !isLoading">
            <div key="empty-state" class="gl-display-flex gl-flex-grow-1 gl-mr-auto gl-ml-auto">
              <gl-empty-state
                :svg-path="$options.emptySvg"
                :svg-height="145"
                :title="$options.i18n.CHAT_EMPTY_STATE_TITLE"
                :description="$options.i18n.CHAT_EMPTY_STATE_DESC"
                class="gl-align-self-center"
              />
            </div>
            <gl-duo-chat-predefined-prompts
              key="predefined-prompts"
              :prompts="predefinedPrompts"
              @click="sendPredefinedPrompt"
            />
          </template>
        </transition-group>
        <transition name="loader">
          <gl-duo-chat-loader v-if="isLoading" :tool-name="toolName" class="gl-px-0!" />
        </transition>
      </section>
    </div>
    <footer
      v-if="isChatAvailable"
      data-testid="chat-footer"
      class="gl-drawer-footer gl-drawer-footer-sticky gl-p-5 gl-border-t gl-bg-gray-10"
      :class="{ 'gl-drawer-body-scrim-on-footer': !scrolledToBottom }"
    >
      <gl-form data-testid="chat-prompt-form" @submit.stop.prevent="sendChatPrompt">
        <gl-form-input-group>
          <div
            class="duo-chat-input gl-flex-grow-1 gl-vertical-align-top gl-max-w-full gl-min-h-8 gl-inset-border-1-gray-400 gl-rounded-base gl-bg-white"
            :data-value="prompt"
          >
            <gl-card
              v-if="shouldShowSlashCommands"
              ref="commands"
              class="slash-commands gl-absolute! gl-translate-y-n100 gl-list-style-none gl-pl-0 gl-w-full gl-shadow-md"
              body-class="gl-p-2!"
            >
              <gl-dropdown-item
                v-for="(command, index) in filteredSlashCommands"
                :key="command.name"
                :class="{ 'active-command': index === activeCommandIndex }"
                @mouseenter.native="activeCommandIndex = index"
                @click="selectSlashCommand(index)"
              >
                <span class="gl-display-flex gl-justify-content-space-between">
                  <span class="gl-display-block">{{ command.name }}</span>
                  <small class="gl-text-gray-500 gl-font-style-italic">{{
                    command.description
                  }}</small>
                </span>
              </gl-dropdown-item>
            </gl-card>

            <gl-form-textarea
              ref="prompt"
              v-model="prompt"
              data-testid="chat-prompt-input"
              class="gl-absolute gl-h-full! gl-py-4! gl-bg-transparent! gl-rounded-top-right-none gl-rounded-bottom-right-none gl-shadow-none!"
              :class="{ 'gl-text-truncate': !prompt }"
              :placeholder="$options.i18n.CHAT_PROMPT_PLACEHOLDER"
              :disabled="isLoading"
              autofocus
              @keydown.enter.exact.native.prevent
              @keyup.native="onInputKeyup"
            />
          </div>
          <template #append>
            <gl-button
              icon="paper-airplane"
              category="primary"
              variant="confirm"
              class="gl-absolute! gl-bottom-2 gl-right-2 gl-rounded-base!"
              type="submit"
              :aria-label="$options.i18n.CHAT_SUBMIT_LABEL"
              :disabled="isLoading"
            />
          </template>
        </gl-form-input-group>
        <gl-form-text
          class="gl-text-gray-400 gl-line-height-20 gl-mt-3"
          data-testid="chat-legal-disclaimer"
          >{{ $options.i18n.CHAT_LEGAL_DISCLAIMER }}</gl-form-text
        >
      </gl-form>
    </footer>
  </aside>
</template>
