<script>
import throttle from 'lodash/throttle';
import emptySvg from '@gitlab/svgs/dist/illustrations/empty-state/empty-activity-md.svg';
import GlDropdownItem from '../../../base/dropdown/dropdown_item.vue';
import GlCard from '../../../base/card/card.vue';
import GlEmptyState from '../../../regions/empty_state/empty_state.vue';
import GlButton from '../../../base/button/button.vue';
import GlAlert from '../../../base/alert/alert.vue';
import GlFormInputGroup from '../../../base/form/form_input_group/form_input_group.vue';
import GlFormTextarea from '../../../base/form/form_textarea/form_textarea.vue';
import GlForm from '../../../base/form/form.vue';
import GlFormText from '../../../base/form/form_text/form_text.vue';
import GlExperimentBadge from '../../experiment_badge/experiment_badge.vue';
import { badgeTypes, badgeTypeValidator } from '../../experiment_badge/constants';
import { SafeHtmlDirective as SafeHtml } from '../../../../directives/safe_html/safe_html';
import GlDuoChatLoader from './components/duo_chat_loader/duo_chat_loader.vue';
import GlDuoChatPredefinedPrompts from './components/duo_chat_predefined_prompts/duo_chat_predefined_prompts.vue';
import GlDuoChatConversation from './components/duo_chat_conversation/duo_chat_conversation.vue';
import GlDuoChatInclude from './duo_chat_include.vue';
import GlDuoChatSelectedIncludes from './duo_chat_selected_include.vue';
import { CHAT_CLEAN_MESSAGE, CHAT_RESET_MESSAGE, CHAT_CLEAR_MESSAGE } from './constants';

export const i18n = {
  CHAT_DEFAULT_TITLE: 'GitLab Duo Chat',
  CHAT_CLOSE_LABEL: 'Close the Code Explanation',
  CHAT_LEGAL_GENERATED_BY_AI: 'Responses generated by AI',
  CHAT_EMPTY_STATE_TITLE: 'Ask a question',
  CHAT_EMPTY_STATE_DESC: 'AI generated explanations will appear here.',
  CHAT_PROMPT_PLACEHOLDER_DEFAULT: 'GitLab Duo Chat',
  CHAT_PROMPT_PLACEHOLDER_WITH_COMMANDS: 'Type "/" for slash commands',
  CHAT_SUBMIT_LABEL: 'Send chat message.',
  CHAT_CANCEL_LABEL: 'Cancel',
  CHAT_LEGAL_DISCLAIMER:
    "May provide inappropriate responses not representative of GitLab's views. Do not input personal data.",
  CHAT_DEFAULT_PREDEFINED_PROMPTS: [
    'How do I change my password in GitLab?',
    'How do I fork a project?',
    'How do I clone a repository?',
    'How do I create a template?',
  ],
};

const isMessage = (item) => Boolean(item) && item?.role;
const isSlashCommand = (command) => Boolean(command) && command?.name && command.description;

// eslint-disable-next-line unicorn/no-array-callback-reference
const itemsValidator = (items) => items.every(isMessage);
// eslint-disable-next-line unicorn/no-array-callback-reference
const slashCommandsValidator = (commands) => commands.every(isSlashCommand);

export default {
  name: 'GlDuoChat',
  components: {
    GlEmptyState,
    GlButton,
    GlAlert,
    GlFormInputGroup,
    GlFormTextarea,
    GlForm,
    GlFormText,
    GlExperimentBadge,
    GlDuoChatLoader,
    GlDuoChatPredefinedPrompts,
    GlDuoChatConversation,
    GlCard,
    GlDropdownItem,
    GlDuoChatInclude,
    GlDuoChatSelectedIncludes,
  },
  directives: {
    SafeHtml,
  },
  props: {
    /**
     * The title of the chat/feature.
     */
    title: {
      type: String,
      required: false,
      default: i18n.CHAT_DEFAULT_TITLE,
    },
    /**
     * Array of messages to display in the chat.
     */
    messages: {
      type: Array,
      required: false,
      default: () => [],
      validator: itemsValidator,
    },
    /**
     * Array of RequestIds that have been canceled.
     */
    canceledRequestIds: {
      type: Array,
      required: false,
      default: () => [],
    },
    /**
     * A non-recoverable error message to display in the chat.
     */
    error: {
      type: String,
      required: false,
      default: '',
    },
    /**
     * Whether the chat is currently fetching a response from AI.
     */
    isLoading: {
      type: Boolean,
      required: false,
      default: false,
    },
    /**
     * Whether the conversational interfaces should be enabled.
     */
    isChatAvailable: {
      type: Boolean,
      required: false,
      default: true,
    },
    /**
     * Whether the insertCode feature should be available.
     */
    enableCodeInsertion: {
      type: Boolean,
      required: false,
      default: false,
    },
    /**
     * Array of predefined prompts to display in the chat to start a conversation.
     */
    predefinedPrompts: {
      type: Array,
      required: false,
      default: () => i18n.CHAT_DEFAULT_PREDEFINED_PROMPTS,
    },
    /**
     * URL to the help page. This is passed down to the `GlExperimentBadge` component.
     */
    badgeHelpPageUrl: {
      type: String,
      required: false,
      default: '',
    },
    /**
     * The type of the badge. This is passed down to the `GlExperimentBadge` component. Refer that component for more information.
     */
    badgeType: {
      type: String || null,
      required: false,
      default: badgeTypes[0],
      validator: badgeTypeValidator,
    },
    /**
     * The current tool's name to display in the loading message while waiting for a response from AI. Refer the `GlDuoChatLoader` component for more information.
     */
    toolName: {
      type: String,
      required: false,
      default: i18n.CHAT_DEFAULT_TITLE,
    },
    /**
     * Array of slash commands to display in the chat.
     */
    slashCommands: {
      type: Array,
      required: false,
      default: () => [],
      validator: slashCommandsValidator,
    },
    /**
     * Whether the header should be displayed.
     */
    showHeader: {
      type: Boolean,
      required: false,
      default: true,
    },
    /**
     * Override the default empty state title text.
     */
    emptyStateTitle: {
      type: String,
      required: false,
      default: i18n.CHAT_EMPTY_STATE_TITLE,
    },
    /**
     * Override the default empty state description text.
     */
    emptyStateDescription: {
      type: String,
      required: false,
      default: i18n.CHAT_EMPTY_STATE_DESC,
    },
    /**
     * Override the default chat prompt placeholder text.
     */
    chatPromptPlaceholder: {
      type: String,
      required: false,
      default: '',
    },
  },
  data() {
    return {
      isHidden: false,
      prompt: '',
      scrolledToBottom: true,
      activeCommandIndex: 0,
      displaySubmitButton: true,
      compositionJustEnded: false,
      showIncludeDropdown: false,
      cursorPosition: 0,
      selectedIncludes: [],
    };
  },
  computed: {
    withSlashCommands() {
      return this.slashCommands.length > 0;
    },
    hasMessages() {
      return this.messages?.length > 0;
    },
    conversations() {
      if (!this.hasMessages) return [];

      return this.messages.reduce(
        (acc, message) => {
          if (message.content === CHAT_RESET_MESSAGE) {
            acc.push([]);
          } else {
            acc[acc.length - 1].push(message);
          }
          return acc;
        },
        [[]]
      );
    },
    lastMessage() {
      return this.messages?.[this.messages.length - 1];
    },
    resetDisabled() {
      if (this.isLoading || !this.hasMessages) {
        return true;
      }
      return this.lastMessage?.content === CHAT_RESET_MESSAGE;
    },
    isStreaming() {
      if (this.canceledRequestIds.includes(this.lastMessage?.requestId)) {
        return false;
      }
      return Boolean(
        (this.lastMessage?.chunks?.length > 0 && !this.lastMessage?.content) ||
          typeof this.lastMessage?.chunkId === 'number'
      );
    },
    filteredSlashCommands() {
      const caseInsensitivePrompt = this.prompt.toLowerCase();
      return this.slashCommands.filter((c) =>
        c.name.toLowerCase().startsWith(caseInsensitivePrompt)
      );
    },
    shouldShowSlashCommands() {
      if (!this.withSlashCommands) return false;
      const caseInsensitivePrompt = this.prompt.toLowerCase();
      const startsWithSlash = caseInsensitivePrompt.startsWith('/');
      const startsWithSlashCommand = this.slashCommands.some((c) =>
        caseInsensitivePrompt.startsWith(c.name)
      );
      return startsWithSlash && this.filteredSlashCommands.length && !startsWithSlashCommand;
    },
    inputPlaceholder() {
      if (this.chatPromptPlaceholder) {
        return this.chatPromptPlaceholder;
      }

      return this.withSlashCommands
        ? i18n.CHAT_PROMPT_PLACEHOLDER_WITH_COMMANDS
        : i18n.CHAT_PROMPT_PLACEHOLDER_DEFAULT;
    },
  },
  watch: {
    isLoading(newVal) {
      if (!newVal && !this.isStreaming) {
        this.displaySubmitButton = true; // Re-enable submit button when loading stops
      }
      this.isHidden = false;
      this.scrollToBottom();
    },
    isStreaming(newVal) {
      if (!newVal && !this.isLoading) {
        this.displaySubmitButton = true; // Re-enable submit button when streaming stops
      }
    },
  },
  created() {
    this.handleScrollingTrottled = throttle(this.handleScrolling, 200); // Assume a 200ms throttle for example
  },
  mounted() {
    this.scrollToBottom();
  },
  methods: {
    compositionEnd() {
      this.compositionJustEnded = true;
    },
    hideChat() {
      this.isHidden = true;
      /**
       * Emitted when clicking the cross in the title and the chat gets closed.
       */
      this.$emit('chat-hidden');
    },
    cancelPrompt() {
      /**
       * Emitted when user clicks the stop button in the textarea
       */

      this.displaySubmitButton = true;
      this.$emit('chat-cancel');
      this.setPromptAndFocus();
    },
    sendChatPrompt() {
      if (!this.displaySubmitButton) {
        return;
      }
      if (this.prompt) {
        if (this.prompt === CHAT_RESET_MESSAGE && this.resetDisabled) {
          return;
        }
        /**
         * Emitted when a new user prompt should be sent out.
         *
         * @param {String} prompt The user prompt to send.
         */

        if (![CHAT_RESET_MESSAGE, CHAT_CLEAN_MESSAGE, CHAT_CLEAR_MESSAGE].includes(this.prompt)) {
          this.displaySubmitButton = false;
        }
        this.$emit('send-chat-prompt', this.prompt.trim());

        this.setPromptAndFocus();
      }
    },
    sendPredefinedPrompt(prompt) {
      this.prompt = prompt;
      this.sendChatPrompt();
    },
    handleScrolling(event) {
      const { scrollTop, offsetHeight, scrollHeight } = event.target;
      this.scrolledToBottom = scrollTop + offsetHeight >= scrollHeight;
    },
    async scrollToBottom() {
      await this.$nextTick();

      this.$refs.anchor?.scrollIntoView?.();
    },
    onTrackFeedback(event) {
      /**
       * Notify listeners about the feedback form submission on a response message.
       * @param {*} event An event, containing the feedback choices and the extended feedback text.
       */
      this.$emit('track-feedback', event);
    },
    sendChatPromptOnEnter(e) {
      const { metaKey, ctrlKey, altKey, shiftKey, isComposing } = e;
      const isModifierKey = metaKey || ctrlKey || altKey || shiftKey;

      return !(isModifierKey || isComposing || this.compositionJustEnded);
    },
    onInputKeyup(e) {
      const { key } = e;

      if (this.showIncludeDropdown) {
        this.$refs.includeComponent.handleKeydown(e);
        this.compositionJustEnded = false;
        return;
      }

      if (this.shouldShowSlashCommands) {
        e.preventDefault();

        if (key === 'Enter') {
          this.selectSlashCommand(this.activeCommandIndex);
        } else if (key === 'ArrowUp') {
          this.prevCommand();
        } else if (key === 'ArrowDown') {
          this.nextCommand();
        } else {
          this.activeCommandIndex = 0;
        }
      } else if (key === 'Enter' && this.sendChatPromptOnEnter(e)) {
        e.preventDefault();

        this.sendChatPrompt();
      }

      this.compositionJustEnded = false;
    },
    prevCommand() {
      this.activeCommandIndex -= 1;
      this.wrapCommandIndex();
    },
    nextCommand() {
      this.activeCommandIndex += 1;
      this.wrapCommandIndex();
    },
    wrapCommandIndex() {
      if (this.activeCommandIndex < 0) {
        this.activeCommandIndex = this.filteredSlashCommands.length - 1;
      } else if (this.activeCommandIndex >= this.filteredSlashCommands.length) {
        this.activeCommandIndex = 0;
      }
    },
    async setPromptAndFocus(prompt = '') {
      this.prompt = prompt;
      await this.$nextTick();
      this.$refs.prompt.$el.focus();
    },
    selectSlashCommand(index) {
      const command = this.filteredSlashCommands[index];
      if (command.shouldSubmit) {
        this.prompt = command.name;
        this.sendChatPrompt();
      } else {
        this.setPromptAndFocus(`${command.name} `);
        if (command.name === '/include') {
          console.log('including dropdown');
          this.showIncludeDropdown = true;
        }
      }
    },
    onInsertCodeSnippet(e) {
      this.$emit('insert-code-snippet', e);
    },

    updateCursorPosition() {
      const textArea = this.$refs.prompt.$el;
      const cursorPosition = textArea.selectionStart;
      const textBeforeCursor = this.prompt.substring(0, cursorPosition);
      const textWidth = this.getTextWidth(textBeforeCursor, getComputedStyle(textArea));
      this.cursorPosition = textWidth;
    },
    getTextWidth(text, style) {
      const canvas = document.createElement('canvas');
      const context = canvas.getContext('2d');
      context.font = `${style.fontSize} ${style.fontFamily}`;
      return context.measureText(text).width;
    },
    handleItemSelected(item) {
      this.selectedIncludes.push(item);
      this.prompt = this.prompt.replace('/include', '').trim();
      this.$nextTick(() => {
        this.$refs.prompt.$el.focus();
      });
    },
    removeInclude(include) {
      this.selectedIncludes = this.selectedIncludes.filter((i) => i.id !== include.id);
    },
  },
  i18n,
  emptySvg,
};
</script>
<template>
  <aside
    v-if="!isHidden"
    id="chat-component"
    class="markdown-code-block duo-chat-drawer duo-chat gl-border-t gl-border-l gl-bottom-0 gl-max-h-full gl-shadow-none"
    role="complementary"
    data-testid="chat-component"
  >
    <header
      v-if="showHeader"
      data-testid="chat-header"
      class="duo-chat-drawer-header duo-chat-drawer-header-sticky gl-z-200 gl-border-b-0 !gl-p-0"
    >
      <div class="drawer-title gl-flex gl-items-center gl-justify-start gl-p-5">
        <h3 class="gl-my-0 gl-text-size-h2">{{ title }}</h3>
        <gl-experiment-badge
          v-if="badgeType"
          :help-page-url="badgeHelpPageUrl"
          :type="badgeType"
          container-id="chat-component"
        />
        <gl-button
          category="tertiary"
          variant="default"
          icon="close"
          size="small"
          class="gl-ml-auto"
          data-testid="chat-close-button"
          :aria-label="$options.i18n.CHAT_CLOSE_LABEL"
          @click="hideChat"
        />
      </div>

      <gl-alert
        :dismissible="false"
        variant="tip"
        :show-icon="false"
        class="legal-warning gl-border-t gl-max-w-full gl-bg-gray-50 gl-p-4 gl-text-center gl-text-gray-700"
        role="alert"
        data-testid="chat-legal-warning"
        >{{ $options.i18n.CHAT_LEGAL_GENERATED_BY_AI }}</gl-alert
      >

      <!--
        @slot Subheader to be rendered right after the title. It is sticky and stays on top of the chat no matter the number of messages.
      -->
      <slot name="subheader"></slot>

      <!-- Ensure that the global error is not scrolled away -->
      <gl-alert
        v-if="error"
        key="error"
        :dismissible="false"
        variant="danger"
        class="!gl-pl-9"
        role="alert"
        data-testid="chat-error"
      >
        <span v-safe-html="error"></span>
      </gl-alert>
    </header>

    <div class="duo-chat-drawer-body" data-testid="chat-history" @scroll="handleScrollingTrottled">
      <transition-group
        tag="section"
        name="message"
        class="duo-chat-history gl-flex gl-flex-col gl-justify-end gl-bg-gray-10"
        :class="[
          {
            'gl-h-full': !hasMessages,
            'force-scroll-bar': hasMessages,
          },
        ]"
      >
        <gl-duo-chat-conversation
          v-for="(conversation, index) in conversations"
          :key="`conversation-${index}`"
          :enable-code-insertion="enableCodeInsertion"
          :messages="conversation"
          :canceled-request-ids="canceledRequestIds"
          :show-delimiter="index > 0"
          @track-feedback="onTrackFeedback"
          @insert-code-snippet="onInsertCodeSnippet"
        />
        <template v-if="!hasMessages && !isLoading">
          <gl-empty-state
            key="empty-state"
            :svg-path="$options.emptySvg"
            :svg-height="145"
            :title="emptyStateTitle"
            :description="emptyStateDescription"
            class="gl-flex-grow gl-justify-center"
          />
          <gl-duo-chat-predefined-prompts
            key="predefined-prompts"
            :prompts="predefinedPrompts"
            @click="sendPredefinedPrompt"
          />
        </template>
        <gl-duo-chat-loader v-if="isLoading" key="loader" :tool-name="toolName" />
        <div key="anchor" ref="anchor" class="scroll-anchor"></div>
      </transition-group>
    </div>
    <footer
      v-if="isChatAvailable"
      data-testid="chat-footer"
      class="duo-chat-drawer-footer duo-chat-drawer-footer-sticky gl-border-t gl-bg-gray-10 gl-p-5"
      :class="{ 'duo-chat-drawer-body-scrim-on-footer': !scrolledToBottom }"
    >
      <gl-form data-testid="chat-prompt-form" @submit.stop.prevent="sendChatPrompt">
        <gl-duo-chat-selected-includes :selected-includes="selectedIncludes" @remove="removeInclude" />
        <gl-form-input-group>
          <div
            class="duo-chat-input gl-min-h-8 gl-max-w-full gl-grow gl-rounded-base gl-bg-white gl-align-top gl-shadow-inner-1-gray-400"
            :data-value="prompt"
          >
            <gl-card
              v-if="shouldShowSlashCommands"
              ref="commands"
              class="slash-commands !gl-absolute gl-w-full -gl-translate-y-full gl-list-none gl-pl-0 gl-shadow-md"
              body-class="!gl-p-2"
            >
              <gl-dropdown-item
                v-for="(command, index) in filteredSlashCommands"
                :key="command.name"
                :class="{ 'active-command': index === activeCommandIndex }"
                @mouseenter.native="activeCommandIndex = index"
                @click="selectSlashCommand(index)"
              >
                <span class="gl-flex gl-justify-between">
                  <span class="gl-block">{{ command.name }}</span>
                  <small class="gl-pl-3 gl-text-right gl-italic gl-text-gray-500">{{
                    command.description
                  }}</small>
                </span>
              </gl-dropdown-item>
            </gl-card>
            <gl-form-textarea
              ref="prompt"
              v-model="prompt"
              data-testid="chat-prompt-input"
              class="gl-absolute !gl-h-full gl-rounded-br-none gl-rounded-tr-none !gl-bg-transparent !gl-py-4 !gl-shadow-none"
              :class="{ 'gl-truncate': !prompt }"
              :placeholder="inputPlaceholder"
              autofocus
              @keydown.enter.exact.native.prevent
              @keyup.native="onInputKeyup"
              @compositionend="compositionEnd"
            />

            <gl-duo-chat-include
              ref="includeComponent"
              :show-include-dropdown="showIncludeDropdown"
              :cursor-position="cursorPosition"
              class="gl-absolute"
              style="top: 0; left: 0"
              @update:showIncludeDropdown="showIncludeDropdown = $event"
              @item-selected="handleItemSelected"
            />
          </div>
          <template #append>
            <gl-button
              v-if="displaySubmitButton"
              icon="paper-airplane"
              category="primary"
              variant="confirm"
              class="!gl-absolute gl-bottom-2 gl-right-2 !gl-rounded-base"
              type="submit"
              data-testid="chat-prompt-submit-button"
              :aria-label="$options.i18n.CHAT_SUBMIT_LABEL"
            />
            <gl-button
              v-else
              icon="stop"
              category="primary"
              variant="default"
              class="!gl-absolute gl-bottom-2 gl-right-2 !gl-rounded-base"
              data-testid="chat-prompt-cancel-button"
              :aria-label="$options.i18n.CHAT_CANCEL_LABEL"
              @click="cancelPrompt"
            />
          </template>
        </gl-form-input-group>
        <gl-form-text
          class="gl-mt-3 gl-leading-20 gl-text-gray-400"
          data-testid="chat-legal-disclaimer"
          >{{ $options.i18n.CHAT_LEGAL_DISCLAIMER }}</gl-form-text
        >
      </gl-form>
    </footer>
  </aside>
</template>
<style scoped>
/* ... (previous styles) ... */
.duo-chat-input {
  position: relative;
}
</style>
